name: CI
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            cd /root/reactionBot
            git pull
            export REACTION_BOT_RELEASE=$(git rev-parse --short HEAD)
            docker build -t reaction_bot:${REACTION_BOT_RELEASE} .
            docker compose up -d
            docker system prune -f
            docker image prune -af
